"""
Project Chimera — The Governor (Judge Agent Safety Layer)

This module implements the "Judge" role of the FastRender Swarm pattern.
It serves as the quality assurance, financial governance, and brand consistency
layer for all Worker outputs.

Spec References:
    - specs/functional.md: AI-016 (Budget Check), AI-017 (Judge Review),
      AI-018 (Confidence Routing), AI-019 (OCC)
    - specs/technical.md: §2.2 (Result Schema), §3 (Financial Ledger),
      §5.5 (Daily Spend Tracker)
    - research/architecture_strategy.md: §The Judge (Gatekeeper),
      §Human Escalation Flow, §Confidence Thresholding
    - SRS: FR 5.2 (CFO Sub-Agent), FR 6.0 (Planner-Worker-Judge),
      FR 6.1 (OCC), NFR 1.0-1.2 (HITL)
"""

from __future__ import annotations

import asyncio
import functools
import logging
import os
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Optional

from pydantic import BaseModel, Field, field_validator

logger = logging.getLogger("chimera.judge.governor")


# =============================================================================
# Exceptions — Spec Ref: AI-016, NFR 1.1
# =============================================================================


class HumanInterventionRequired(Exception):
    """
    Raised when a Worker result fails the Judge's confidence threshold
    or triggers a sensitive topic filter, requiring HITL review.

    Spec Ref: NFR 1.1 (Automated Escalation Logic)
    """

    def __init__(
        self,
        result_id: str,
        reason: str,
        confidence_score: float,
        reasoning_trace: str,
    ):
        self.result_id = result_id
        self.reason = reason
        self.confidence_score = confidence_score
        self.reasoning_trace = reasoning_trace
        super().__init__(
            f"HITL Required for result {result_id}: {reason} "
            f"(confidence: {confidence_score:.2f})"
        )


class BudgetExceededError(Exception):
    """
    Raised when a proposed transaction would exceed the agent's daily
    spend limit. The transaction is NOT executed.

    Spec Ref: FR 5.2 (CFO Sub-Agent), AI-016
    """

    def __init__(
        self,
        agent_id: str,
        proposed_amount: float,
        current_spend: float,
        daily_limit: float,
    ):
        self.agent_id = agent_id
        self.proposed_amount = proposed_amount
        self.current_spend = current_spend
        self.daily_limit = daily_limit
        super().__init__(
            f"Budget exceeded for agent {agent_id}: "
            f"proposed ${proposed_amount:.2f} + current ${current_spend:.2f} "
            f"> limit ${daily_limit:.2f}"
        )


class OCCConflictError(Exception):
    """
    Raised when Optimistic Concurrency Control detects that the GlobalState
    has drifted since the Worker began its task.

    Spec Ref: FR 6.1, AI-019
    """

    def __init__(self, task_id: str, expected_version: int, actual_version: int):
        self.task_id = task_id
        self.expected_version = expected_version
        self.actual_version = actual_version
        super().__init__(
            f"OCC conflict for task {task_id}: "
            f"expected version {expected_version}, found {actual_version}"
        )


# =============================================================================
# Enums — Confidence Routing Tiers
# =============================================================================


class ConfidenceDecision(str, Enum):
    """
    Routing decisions based on confidence scoring.
    Spec Ref: NFR 1.0, NFR 1.1
    """

    AUTO_APPROVE = "auto_approve"  # > 0.90 (or > 0.95 for financial)
    ASYNC_APPROVAL = "async_approval"  # 0.70 - 0.90
    REJECT_RETRY = "reject_retry"  # < 0.70


class ReviewDecision(str, Enum):
    """HITL reviewer outcomes. Spec Ref: NFR 1.1"""

    APPROVED = "approved"
    EDITED = "edited"
    REJECTED = "rejected"


# =============================================================================
# Pydantic Models — Confidence Scoring & Validation
# =============================================================================


class ConfidenceScoredAction(BaseModel):
    """
    Every action generated by a Worker MUST include this metadata.
    The Judge uses these fields to route the result through the
    confidence-based HITL framework.

    Spec Ref: NFR 1.0, specs/technical.md §2.2
    """

    result_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this result.",
    )
    task_id: str = Field(
        ..., description="Reference to the originating Task."
    )
    agent_id: str = Field(
        ..., description="The Chimera Agent this result belongs to."
    )
    worker_id: str = Field(
        ..., description="Identifier of the Worker that produced this result."
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description=(
            "LLM-estimated confidence in the quality and safety of this result. "
            "Drives HITL routing per NFR 1.0."
        ),
    )
    reasoning_trace: str = Field(
        ...,
        min_length=10,
        description=(
            "Chain-of-thought explanation from the Worker. "
            "Required for audit trail and HITL review."
        ),
    )
    artifact_type: str = Field(
        ...,
        description="Type of the produced artifact: text, image_url, video_url, transaction, analysis.",
    )
    artifact_body: str = Field(
        ..., description="The generated content or URL reference."
    )
    sensitive_topics_detected: list[str] = Field(
        default_factory=list,
        description=(
            "Sensitive topic categories detected. "
            "Presence forces HITL routing regardless of confidence. "
            "Spec Ref: NFR 1.2"
        ),
    )
    state_version_at_start: int = Field(
        ...,
        ge=0,
        description="GlobalState version when Worker began. For OCC validation.",
    )
    execution_duration_ms: int = Field(
        default=0,
        ge=0,
        description="Wall-clock time the Worker spent on this task.",
    )
    tools_invoked: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Audit log of MCP tool invocations during execution.",
    )

    @field_validator("confidence_score")
    @classmethod
    def validate_confidence_precision(cls, v: float) -> float:
        """Ensure confidence score has at most 4 decimal places."""
        return round(v, 4)


class TransactionProposal(BaseModel):
    """
    A financial transaction proposed by a Worker that must be validated
    by the CFO Judge before execution.

    Spec Ref: FR 5.1, FR 5.2, AI-016
    """

    agent_id: str = Field(..., description="Agent initiating the transaction.")
    to_address: str = Field(..., description="Recipient wallet address.")
    amount_usdc: float = Field(
        ..., gt=0, description="Amount in USDC to transfer."
    )
    network: str = Field(
        default="base", description="Blockchain network (default: Base)."
    )
    purpose: str = Field(
        ..., description="Business justification for the transaction."
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence in the transaction's validity.",
    )
    reasoning_trace: str = Field(
        ..., description="Chain-of-thought justification."
    )


# =============================================================================
# The Budget Check Decorator — Spec Ref: FR 5.2, AI-016
# =============================================================================


def budget_check(func: Callable) -> Callable:
    """
    Decorator that enforces daily spend limits before executing any
    financial transaction. Uses Redis-backed daily spend tracking.

    MUST be applied to any function that calls coinbase-agentkit
    send_payment, native_transfer, or deploy_token.

    Spec Ref: FR 5.2 (CFO Sub-Agent), AI-016
    Architecture Ref: research/architecture_strategy.md §Human Escalation Flow

    Workflow:
        1. Read current daily_spend from Redis hash chimera:daily_spend:{agent_id}
        2. If daily_spend + proposed_amount > MAX_DAILY_LIMIT → raise BudgetExceededError
        3. If confidence_score < FINANCIAL_CONFIDENCE_THRESHOLD (0.95) → raise HumanInterventionRequired
        4. Execute the transaction
        5. Atomically update daily_spend in Redis via HINCRBYFLOAT
    """

    @functools.wraps(func)
    async def wrapper(*args: Any, **kwargs: Any) -> Any:
        # Extract the transaction proposal from arguments
        proposal: TransactionProposal | None = kwargs.get("proposal") or (
            args[1] if len(args) > 1 and isinstance(args[1], TransactionProposal) else None
        )
        redis_client = kwargs.get("redis_client") or (
            args[0].redis_client if hasattr(args[0], "redis_client") else None
        )

        if proposal is None:
            raise ValueError(
                "budget_check requires a TransactionProposal argument. "
                "Spec Ref: AI-016"
            )

        if redis_client is None:
            raise ValueError(
                "budget_check requires a redis_client. "
                "Spec Ref: specs/technical.md §5.5"
            )

        max_daily_limit = float(
            os.environ.get("MAX_DAILY_LIMIT_USDC", "50.0")
        )
        financial_confidence_threshold = float(
            os.environ.get("FINANCIAL_CONFIDENCE_THRESHOLD", "0.95")
        )

        # Step 1: Read current daily spend from Redis
        # Spec Ref: specs/technical.md §5.5 (Daily Spend Tracker)
        spend_key = f"chimera:daily_spend:{proposal.agent_id}"
        current_spend_raw = await redis_client.hget(spend_key, "total_usdc")
        current_spend = float(current_spend_raw) if current_spend_raw else 0.0

        # Step 2: Check budget limit
        if current_spend + proposal.amount_usdc > max_daily_limit:
            logger.warning(
                "Budget check FAILED for agent %s: $%.2f + $%.2f > $%.2f",
                proposal.agent_id,
                current_spend,
                proposal.amount_usdc,
                max_daily_limit,
            )
            raise BudgetExceededError(
                agent_id=proposal.agent_id,
                proposed_amount=proposal.amount_usdc,
                current_spend=current_spend,
                daily_limit=max_daily_limit,
            )

        # Step 3: Check financial confidence threshold (higher than standard 0.90)
        if proposal.confidence_score < financial_confidence_threshold:
            logger.info(
                "Financial HITL triggered for agent %s: confidence %.2f < %.2f",
                proposal.agent_id,
                proposal.confidence_score,
                financial_confidence_threshold,
            )
            raise HumanInterventionRequired(
                result_id=f"tx-{proposal.agent_id}-{uuid.uuid4().hex[:8]}",
                reason=(
                    f"Financial transaction confidence {proposal.confidence_score:.2f} "
                    f"below financial threshold {financial_confidence_threshold}"
                ),
                confidence_score=proposal.confidence_score,
                reasoning_trace=proposal.reasoning_trace,
            )

        # Step 4: Execute the wrapped function (the actual transaction)
        result = await func(*args, **kwargs)

        # Step 5: Atomically update daily spend in Redis
        # Spec Ref: specs/technical.md §5.5
        await redis_client.hincrbyfloat(
            spend_key, "total_usdc", proposal.amount_usdc
        )
        await redis_client.hincrby(spend_key, "tx_count", 1)
        await redis_client.hset(
            spend_key,
            "last_updated",
            datetime.now(timezone.utc).isoformat(),
        )

        logger.info(
            "Transaction approved for agent %s: $%.2f (new daily total: $%.2f)",
            proposal.agent_id,
            proposal.amount_usdc,
            current_spend + proposal.amount_usdc,
        )

        return result

    return wrapper


# =============================================================================
# The Governor — Core Judge Agent
# =============================================================================


class Governor:
    """
    The Governor is the central Judge Agent in the FastRender Swarm.
    It validates all Worker outputs before they can be committed to
    the GlobalState or published externally.

    Spec Ref:
        - SRS §3.1.3 (The Judge)
        - specs/functional.md AI-017, AI-018, AI-019
        - research/architecture_strategy.md §Confidence Thresholding

    Responsibilities:
        1. Confidence-based routing (Auto/HITL/Reject)
        2. Sensitive topic detection → force HITL
        3. OCC state_version validation
        4. Financial transaction governance (CFO pattern)
        5. Brand/visual consistency verification
    """

    # Thresholds — Spec Ref: NFR 1.0, NFR 1.1
    DEFAULT_AUTO_APPROVE_THRESHOLD: float = 0.90
    DEFAULT_HITL_THRESHOLD: float = 0.70
    FINANCIAL_CONFIDENCE_THRESHOLD: float = 0.95

    # Sensitive topics that force HITL — Spec Ref: NFR 1.2
    SENSITIVE_TOPICS: set[str] = {
        "politics",
        "health_advice",
        "financial_advice",
        "legal_claims",
        "religion",
        "violence",
        "adult_content",
    }

    def __init__(
        self,
        redis_client: Any,
        db_client: Any | None = None,
        mcp_client: Any | None = None,
        auto_approve_threshold: float | None = None,
        hitl_threshold: float | None = None,
    ):
        """
        Initialize the Governor.

        Args:
            redis_client: Async Redis client for queue operations and spend tracking.
            db_client: Async PostgreSQL client for ledger operations.
            mcp_client: MCPClient for tool invocations (e.g., vision model calls).
            auto_approve_threshold: Override for auto-approve threshold (default 0.90).
            hitl_threshold: Override for HITL lower bound (default 0.70).
        """
        self.redis_client = redis_client
        self.db_client = db_client
        self.mcp_client = mcp_client
        self.auto_approve_threshold = (
            auto_approve_threshold
            or float(os.environ.get("CONFIDENCE_THRESHOLD", str(self.DEFAULT_AUTO_APPROVE_THRESHOLD)))
        )
        self.hitl_threshold = (
            hitl_threshold
            or float(os.environ.get("HITL_THRESHOLD", str(self.DEFAULT_HITL_THRESHOLD)))
        )

    # -------------------------------------------------------------------------
    # Confidence Routing — Spec Ref: NFR 1.0, NFR 1.1, NFR 1.2
    # -------------------------------------------------------------------------

    def evaluate_confidence(
        self, action: ConfidenceScoredAction
    ) -> ConfidenceDecision:
        """
        Evaluate a Worker's result and determine the routing decision.

        Spec Ref: NFR 1.0 (Confidence Scoring), NFR 1.1 (Escalation Logic)

        Rules:
            1. If sensitive topics detected → always ASYNC_APPROVAL (force HITL)
            2. confidence > auto_approve_threshold → AUTO_APPROVE
            3. hitl_threshold <= confidence <= auto_approve_threshold → ASYNC_APPROVAL
            4. confidence < hitl_threshold → REJECT_RETRY
        """
        # Rule 1: Sensitive topic filter overrides confidence — NFR 1.2
        if action.sensitive_topics_detected:
            detected = set(action.sensitive_topics_detected) & self.SENSITIVE_TOPICS
            if detected:
                logger.info(
                    "Sensitive topics detected for result %s: %s → forcing HITL",
                    action.result_id,
                    detected,
                )
                return ConfidenceDecision.ASYNC_APPROVAL

        # Rule 2-4: Confidence-based routing — NFR 1.1
        if action.confidence_score > self.auto_approve_threshold:
            return ConfidenceDecision.AUTO_APPROVE
        elif action.confidence_score >= self.hitl_threshold:
            return ConfidenceDecision.ASYNC_APPROVAL
        else:
            return ConfidenceDecision.REJECT_RETRY

    # -------------------------------------------------------------------------
    # OCC Validation — Spec Ref: FR 6.1, AI-019
    # -------------------------------------------------------------------------

    async def validate_state_version(
        self,
        task_id: str,
        agent_id: str,
        state_version_at_start: int,
    ) -> bool:
        """
        Validate that the GlobalState has not drifted since the Worker
        began processing. Implements Optimistic Concurrency Control.

        Spec Ref: FR 6.1, AI-019
        Architecture Ref: research/architecture_strategy.md §OCC

        Returns:
            True if state is consistent, False if drifted.

        Raises:
            OCCConflictError if state has drifted.
        """
        # Read current state version from Redis
        state_key = f"chimera:state_version:{agent_id}"
        current_version_raw = await self.redis_client.get(state_key)
        current_version = int(current_version_raw) if current_version_raw else 0

        if current_version != state_version_at_start:
            logger.warning(
                "OCC conflict for task %s: expected v%d, found v%d",
                task_id,
                state_version_at_start,
                current_version,
            )
            raise OCCConflictError(
                task_id=task_id,
                expected_version=state_version_at_start,
                actual_version=current_version,
            )

        return True

    # -------------------------------------------------------------------------
    # Transaction Validation — The CFO Pattern
    # Spec Ref: FR 5.2, AI-016
    # -------------------------------------------------------------------------

    @budget_check
    async def validate_transaction(
        self,
        proposal: TransactionProposal,
        redis_client: Any | None = None,
    ) -> dict[str, Any]:
        """
        Validate and authorize a financial transaction proposed by a Worker.
        This implements the "CFO" sub-agent pattern.

        The @budget_check decorator handles:
            - Daily spend limit enforcement via Redis
            - Financial confidence threshold (0.95, higher than standard 0.90)
            - BudgetExceededError / HumanInterventionRequired exceptions

        If the decorator allows execution, this method performs additional
        validation and returns the authorization payload.

        Spec Ref: FR 5.2, AI-016, specs/technical.md §5.5

        Args:
            proposal: The TransactionProposal to validate.
            redis_client: Override Redis client (used by decorator).

        Returns:
            Authorization dict with tx metadata for the Worker to execute.

        Raises:
            BudgetExceededError: If daily limit would be exceeded.
            HumanInterventionRequired: If confidence < 0.95 for financial ops.
        """
        authorization = {
            "authorized": True,
            "authorization_id": str(uuid.uuid4()),
            "agent_id": proposal.agent_id,
            "amount_usdc": proposal.amount_usdc,
            "to_address": proposal.to_address,
            "network": proposal.network,
            "authorized_at": datetime.now(timezone.utc).isoformat(),
            "governor_reasoning": (
                f"Transaction approved. Purpose: {proposal.purpose}. "
                f"Confidence: {proposal.confidence_score:.2f}. "
                f"Amount within daily budget."
            ),
        }

        logger.info(
            "CFO authorized transaction %s: $%.2f USDC to %s on %s",
            authorization["authorization_id"],
            proposal.amount_usdc,
            proposal.to_address,
            proposal.network,
        )

        return authorization

    # -------------------------------------------------------------------------
    # Brand Consistency Vision — Spec Ref: FR 3.1, AI-008
    # -------------------------------------------------------------------------

    async def validate_brand_consistency(
        self,
        generated_image_url: str,
        reference_image_id: str,
        agent_id: str,
    ) -> dict[str, Any]:
        """
        Verify that a generated image is visually consistent with the
        agent's established character reference using a Vision-capable model.

        Uses Gemini 3 Flash via MCP to compare the generated image against
        the reference image stored in the agent's persona config.

        Spec Ref: FR 3.1 (Character Consistency Lock), AI-008
        SRS: §4.3 FR 3.1, Developer Notes

        Args:
            generated_image_url: URL of the newly generated image.
            reference_image_id: ID to retrieve the canonical reference image.
            agent_id: The Chimera Agent whose brand is being verified.

        Returns:
            Dict with:
                - is_consistent (bool): Whether the images match.
                - confidence (float): Model's confidence in the assessment.
                - reasoning (str): Explanation of the decision.

        Raises:
            HumanInterventionRequired: If consistency cannot be verified.
        """
        if self.mcp_client is None:
            logger.warning(
                "MCP client not available for brand consistency check. "
                "Falling back to HITL."
            )
            raise HumanInterventionRequired(
                result_id=f"brand-{agent_id}-{uuid.uuid4().hex[:8]}",
                reason="MCP client unavailable for vision-based brand check",
                confidence_score=0.0,
                reasoning_trace="Cannot verify brand consistency without MCP/Vision model access.",
            )

        # Construct the vision prompt for Gemini 3 Flash
        # Spec Ref: SRS §4.3 Developer Notes
        vision_prompt = (
            "You are a brand consistency validator for an AI influencer network. "
            "Compare the two images provided:\n"
            "- Image A (generated): The newly created content image.\n"
            "- Image B (reference): The canonical character reference.\n\n"
            "Evaluate whether the person/character in Image A looks like the same "
            "person/character in Image B. Consider: facial features, style, "
            "color palette, and overall brand identity.\n\n"
            "Respond in JSON format:\n"
            '{"is_consistent": true/false, "confidence": 0.0-1.0, '
            '"reasoning": "explanation"}'
        )

        try:
            # Route through MCP — Rule 2 enforcement
            # Spec Ref: .cursor/rules/project-chimera.mdc Rule 2
            result = await self.mcp_client.call_tool(
                server_name="mcp-server-gemini",
                tool_name="analyze_images",
                arguments={
                    "prompt": vision_prompt,
                    "image_urls": [generated_image_url],
                    "reference_image_id": reference_image_id,
                    "model": "gemini-3-flash",
                    "response_format": "json",
                },
            )

            # Parse the vision model response
            validation_result = {
                "is_consistent": result.get("is_consistent", False),
                "confidence": result.get("confidence", 0.0),
                "reasoning": result.get("reasoning", "No reasoning provided."),
                "agent_id": agent_id,
                "generated_image_url": generated_image_url,
                "reference_image_id": reference_image_id,
                "validated_at": datetime.now(timezone.utc).isoformat(),
            }

            if not validation_result["is_consistent"]:
                logger.warning(
                    "Brand consistency FAILED for agent %s: %s",
                    agent_id,
                    validation_result["reasoning"],
                )

            return validation_result

        except Exception as e:
            logger.error(
                "Brand consistency check failed for agent %s: %s",
                agent_id,
                str(e),
            )
            # On failure, escalate to human — safety first
            raise HumanInterventionRequired(
                result_id=f"brand-{agent_id}-{uuid.uuid4().hex[:8]}",
                reason=f"Vision model error during brand check: {str(e)}",
                confidence_score=0.0,
                reasoning_trace=f"Exception in brand validation: {str(e)}",
            )

    # -------------------------------------------------------------------------
    # Master Review Pipeline — Combines all checks
    # Spec Ref: AI-017, AI-018, AI-019
    # -------------------------------------------------------------------------

    async def review_result(
        self,
        action: ConfidenceScoredAction,
    ) -> dict[str, Any]:
        """
        The master review pipeline. Every Worker result passes through this
        method before it can be committed to GlobalState.

        Spec Ref: AI-017 (Judge Review), AI-018 (Confidence Routing),
                  AI-019 (OCC)

        Pipeline:
            1. Validate OCC state_version
            2. Evaluate confidence routing
            3. Route based on decision:
               - AUTO_APPROVE → commit
               - ASYNC_APPROVAL → push to HITL queue
               - REJECT_RETRY → re-queue for Planner

        Returns:
            Dict with decision, routing info, and audit metadata.

        Raises:
            OCCConflictError: If state has drifted.
            HumanInterventionRequired: If HITL review needed.
        """
        review_id = str(uuid.uuid4())

        logger.info(
            "Reviewing result %s for agent %s (confidence: %.2f)",
            action.result_id,
            action.agent_id,
            action.confidence_score,
        )

        # Step 1: OCC Validation — Spec Ref: FR 6.1, AI-019
        await self.validate_state_version(
            task_id=action.task_id,
            agent_id=action.agent_id,
            state_version_at_start=action.state_version_at_start,
        )

        # Step 2: Confidence Routing — Spec Ref: NFR 1.0, NFR 1.1
        decision = self.evaluate_confidence(action)

        review_record = {
            "review_id": review_id,
            "result_id": action.result_id,
            "task_id": action.task_id,
            "agent_id": action.agent_id,
            "confidence_score": action.confidence_score,
            "decision": decision.value,
            "sensitive_topics": action.sensitive_topics_detected,
            "reasoning_trace": action.reasoning_trace,
            "reviewed_at": datetime.now(timezone.utc).isoformat(),
        }

        # Step 3: Route based on decision
        if decision == ConfidenceDecision.AUTO_APPROVE:
            logger.info(
                "AUTO-APPROVED result %s (confidence: %.2f)",
                action.result_id,
                action.confidence_score,
            )
            review_record["action"] = "committed"
            # In full implementation: commit to GlobalState, increment state_version

        elif decision == ConfidenceDecision.ASYNC_APPROVAL:
            logger.info(
                "HITL ESCALATION for result %s (confidence: %.2f, topics: %s)",
                action.result_id,
                action.confidence_score,
                action.sensitive_topics_detected,
            )
            # Push to HITL queue — Spec Ref: specs/technical.md §5.2
            await self.redis_client.xadd(
                "chimera:hitl_queue",
                {
                    "review_id": review_id,
                    "result_id": action.result_id,
                    "agent_id": action.agent_id,
                    "confidence_score": str(action.confidence_score),
                    "reasoning_trace": action.reasoning_trace,
                    "artifact_type": action.artifact_type,
                    "artifact_body": action.artifact_body,
                    "sensitive_topics": ",".join(action.sensitive_topics_detected),
                },
            )
            review_record["action"] = "escalated_to_hitl"

            raise HumanInterventionRequired(
                result_id=action.result_id,
                reason=(
                    f"Confidence {action.confidence_score:.2f} in HITL range "
                    f"[{self.hitl_threshold}, {self.auto_approve_threshold}]"
                    + (
                        f" | Sensitive topics: {action.sensitive_topics_detected}"
                        if action.sensitive_topics_detected
                        else ""
                    )
                ),
                confidence_score=action.confidence_score,
                reasoning_trace=action.reasoning_trace,
            )

        elif decision == ConfidenceDecision.REJECT_RETRY:
            logger.warning(
                "REJECTED result %s (confidence: %.2f) → re-queuing",
                action.result_id,
                action.confidence_score,
            )
            review_record["action"] = "rejected_for_retry"
            # In full implementation: push retry signal to Planner via task_queue

        return review_record
