"""
Project Chimera — Planner Agent (The Strategist)

This module implements the "Planner" role of the FastRender Swarm pattern.
The Planner decomposes high-level campaign goals into executable tasks
using an LLM (via OpenRouter), and manages the GlobalState.

Spec References:
    - specs/functional.md: MA-001 (Campaign Decomposition), MA-002 (Dynamic Re-planning),
      MA-003 (Sub-Planners), MA-004 (Auto-scaling), MA-005 (Fleet-wide Policy)
    - specs/technical.md: §2.1 (Task Schema), §5.2 (Queue Definitions)
    - SRS: §3.1.1 (The Planner), FR 6.0
    - research/architecture_strategy.md: §The Planner (Strategist)

Implementation Status: LIVE — Uses OpenRouter LLM for goal decomposition.
"""

from __future__ import annotations

import asyncio
import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field

logger = logging.getLogger("chimera.swarm.planner")


# =============================================================================
# Data Models — Spec Ref: specs/technical.md §2.1
# =============================================================================


class CampaignGoal(BaseModel):
    """
    High-level campaign goal from the Network Operator.
    Spec Ref: MA-001, SRS §3.1.1
    """

    campaign_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    goal_description: str = Field(
        ..., description="Natural language campaign objective."
    )
    agent_id: str = Field(..., description="Chimera Agent to execute this campaign.")
    priority: str = Field(default="medium", description="Campaign priority level.")
    budget_usdc: float = Field(default=0.0, ge=0, description="Total campaign budget.")
    target_platforms: list[str] = Field(default_factory=lambda: ["twitter"])
    constraints: list[str] = Field(
        default_factory=list,
        description="Behavioral constraints from SOUL.md directives.",
    )


class TaskDAGNode(BaseModel):
    """
    A node in the task Directed Acyclic Graph generated by the Planner.
    Spec Ref: SRS §3.1.1 (DAG generation)
    """

    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_type: str
    goal_description: str
    dependencies: list[str] = Field(
        default_factory=list,
        description="task_ids that must complete before this task can execute.",
    )
    priority: str = "medium"
    estimated_cost_usdc: float = 0.0


# =============================================================================
# Planner Service — Spec Ref: FR 6.0, MA-001
# =============================================================================

# The system prompt that turns an LLM into a strategic planner
PLANNER_SYSTEM_PROMPT = """You are the Planner Agent in Project Chimera's FastRender Swarm.
Your role is to decompose high-level campaign goals into concrete, executable sub-tasks.

You MUST return a JSON array of task objects. Each task has:
- "task_type": one of ["generate_content", "reply_comment", "trend_analysis", "image_generation", "video_generation"]
- "goal_description": clear, specific instruction for the Worker agent
- "priority": one of ["critical", "high", "medium", "low"]
- "estimated_cost_usdc": estimated cost (0.0 for text-only tasks)

Rules:
1. Break the goal into 3-6 atomic tasks that a Worker can execute independently.
2. Order tasks logically — research/analysis first, then creation, then publishing.
3. Each task description must be specific enough for an AI agent to execute without ambiguity.
4. Consider the target platforms and persona constraints provided.
5. ALWAYS include at least one trend_analysis task to inform content creation.

Return ONLY a JSON array. No explanation."""


class PlannerService:
    """
    The Strategist: Decomposes campaign goals into task DAGs using LLM reasoning.

    Spec Ref:
        - SRS §3.1.1 (The Planner)
        - specs/functional.md MA-001 through MA-005
        - research/architecture_strategy.md §The Planner (Strategist)
    """

    def __init__(
        self,
        llm_client: Any,
        redis_client: Any | None = None,
        mcp_client: Any | None = None,
    ):
        """
        Args:
            llm_client: LLMClient instance for reasoning.
            redis_client: Async Redis client for task queue operations.
            mcp_client: MCPClient for resource polling and context fetching.
        """
        self.llm_client = llm_client
        self.redis_client = redis_client
        self.mcp_client = mcp_client
        self._active_dags: dict[str, list[TaskDAGNode]] = {}

    async def decompose_goal(self, goal: CampaignGoal) -> list[TaskDAGNode]:
        """
        Decompose a high-level campaign goal into a task DAG using the LLM.

        Spec Ref: MA-001, SRS §3.1.1
        """
        logger.info(
            "Decomposing goal for agent %s: %s",
            goal.agent_id,
            goal.goal_description[:100],
        )

        user_prompt = (
            f"Campaign Goal: {goal.goal_description}\n"
            f"Target Platforms: {', '.join(goal.target_platforms)}\n"
            f"Priority: {goal.priority}\n"
            f"Budget: ${goal.budget_usdc:.2f} USDC\n"
            f"Constraints: {', '.join(goal.constraints) if goal.constraints else 'None'}\n\n"
            f"Decompose this into executable sub-tasks."
        )

        try:
            raw_tasks = await self.llm_client.generate_json(
                system_prompt=PLANNER_SYSTEM_PROMPT,
                user_prompt=user_prompt,
                temperature=0.4,
            )

            # Ensure we have a list
            if isinstance(raw_tasks, dict):
                raw_tasks = raw_tasks.get("tasks", [raw_tasks])

            dag: list[TaskDAGNode] = []
            for i, task_data in enumerate(raw_tasks):
                if isinstance(task_data, dict):
                    # Validate task_type against allowed values
                    task_type = task_data.get("task_type", "generate_content")
                    valid_types = {
                        "generate_content", "reply_comment", "trend_analysis",
                        "image_generation", "video_generation", "execute_transaction",
                        "deploy_token", "memory_update",
                    }
                    if task_type not in valid_types:
                        task_type = "generate_content"

                    node = TaskDAGNode(
                        task_type=task_type,
                        goal_description=task_data.get(
                            "goal_description",
                            task_data.get("description", f"Task {i+1}"),
                        ),
                        priority=task_data.get("priority", goal.priority),
                        estimated_cost_usdc=float(
                            task_data.get("estimated_cost_usdc", 0.0)
                        ),
                    )
                    dag.append(node)

            if not dag:
                # Fallback: create a basic task if LLM returns empty
                dag = [
                    TaskDAGNode(
                        task_type="trend_analysis",
                        goal_description=f"Research trends related to: {goal.goal_description}",
                        priority=goal.priority,
                    ),
                    TaskDAGNode(
                        task_type="generate_content",
                        goal_description=f"Create content for: {goal.goal_description}",
                        priority=goal.priority,
                    ),
                ]

            self._active_dags[goal.campaign_id] = dag

            logger.info(
                "Decomposed goal into %d tasks for agent %s",
                len(dag),
                goal.agent_id,
            )

            return dag

        except Exception as e:
            logger.error("Goal decomposition failed: %s", str(e))
            # Return a minimal fallback DAG
            fallback = [
                TaskDAGNode(
                    task_type="generate_content",
                    goal_description=goal.goal_description,
                    priority=goal.priority,
                ),
            ]
            self._active_dags[goal.campaign_id] = fallback
            return fallback

    async def enqueue_tasks(
        self, agent_id: str, dag: list[TaskDAGNode]
    ) -> list[str]:
        """
        Push decomposed tasks to the agent's Redis task queue.
        Spec Ref: MA-001, specs/technical.md §5.2

        If Redis is not available, returns task IDs for in-memory processing.
        """
        message_ids: list[str] = []

        if self.redis_client is None:
            # In-memory mode (no Redis) — return task IDs directly
            for node in dag:
                message_ids.append(node.task_id)
            logger.info(
                "Enqueued %d tasks in-memory for agent %s (no Redis)",
                len(message_ids),
                agent_id,
            )
            return message_ids

        stream_key = f"chimera:task_queue:{agent_id}"
        for node in dag:
            msg_id = await self.redis_client.xadd(
                stream_key,
                {
                    "task_id": node.task_id,
                    "task_type": node.task_type,
                    "goal_description": node.goal_description,
                    "priority": node.priority,
                    "dependencies": ",".join(node.dependencies),
                },
            )
            message_ids.append(msg_id)

        logger.info("Enqueued %d tasks for agent %s", len(message_ids), agent_id)
        return message_ids

    async def handle_context_change(
        self, campaign_id: str, change_event: dict[str, Any]
    ) -> list[TaskDAGNode]:
        """
        React to a context change by dynamically re-planning.
        Spec Ref: MA-002, SRS §3.1.1 (Dynamic Re-planning)
        """
        logger.info(
            "Context change for campaign %s: %s",
            campaign_id,
            change_event.get("type", "unknown"),
        )
        current_dag = self._active_dags.get(campaign_id, [])
        return current_dag
